#
# Module manifest for module 'module'
#
# Generated by: pwujczyk
#
# Generated on: 4/27/2021 4:51:11 PM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ProductivityTools.AzureAutomation.psm1'

# Version number of this module.
ModuleVersion = '0.0.9'

# ID used to uniquely identify this module
GUID = '05b1ae2f-d068-401c-903f-645e0260abcd'

# Author of this module
Author = 'Pawel Wujczyk'

# Company or vendor of this module
CompanyName = 'ProductivityTools.tech'

# Description of the functionality provided by this module
Description = 'Abstract layer on the Powershell azure cmdlets.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('ProductivityTools.MasterConfiguration')

# Functions to export from this module
FunctionsToExport = @('Create-ResourceGroup',
	'Remove-ResourceGroup',
	'Create-StorageAccount',
	'Remove-StorageAccount',
	'Create-StorageContainer',
	'Remove-StorageContainer',
	'Set-StorageAccountCustomDomain',
	'Push-FileToAzureBlobStorage',
    'Get-AzureBlobStorageFiles',
    'Get-AzureBlobStorageFilesNames'
    'Remove-AzureBlobStorageFile'
)

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{
    
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure','Automation')
    
        # A URL to the main website for this project.
        ProjectUri = 'http://productivitytools.tech/ss/'
    
        # A URL to an icon representing this module.
        IconUri = 'http://cdn.productivitytools.tech/images/PT/ProductivityTools_blue_85px_3.png'
            } # End of PSData hashtable
    } # End of PrivateData hashtable   

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

